version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: akuma
    image: akuma:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env