version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: akuma
    image: akuma:latest
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    