version: "3.8"
services:
  akuma-collector:
    image: kamuicm/akuma-collector
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    environment:
      - NODE_ENV=production
    env_file:
      - .env